name: fuzzing-needswork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  build:
    uses: ./.github/workflows/workflow-for-fuzzing-build.yml

  fuzzing-needswork:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        lang: [af, ar, be, ca, da, es, gn, grc, hi, kl, mr, nl, om, or, pa, pt, ro, shn, si, sv, ta, te, tk, tn, vi]
    uses: ./.github/workflows/workflow-for-fuzzing.yml
    with:
      lang: ${{ matrix.lang }}
